---
---
# ------------------------PANDAS----------------------
---
---

## What is Numpy?
### It aims to provide an array object that is up to 50x faster than the traditional python list.

## Why array is faster than the usual list?
### Beacuse they are stored in the one continious memory unlike list, so the process to access and manupilate became faster than the list  


#### Normal / 1D Array

In [7]:
import numpy

arr=numpy.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
import numpy as np
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

#### 2D array

In [8]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
print(arr1)

[[1 2 3]
 [4 5 6]]


#### Custom / Special Creation function

In [12]:
# Array with all zeroes 
arr2=np.zeros(5)
arr2

array([0., 0., 0., 0., 0.])

In [18]:
# 2X3 matrix of 1
arr3=np.ones((2,3))
arr3
arr4=np.ones((10,10))
arr4

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### Range creation 

In [19]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.linspace(1,10,5) #5 values between 0 and 1
#np.linespace(from,to,numberofelements)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#### Accessing elements and modifying them as like list

In [23]:
arr=np.array([10,20,30])

In [25]:
print(arr[1])

20


In [26]:
arr[1]=73

In [27]:
print(arr[1])

73


In [29]:
arr[1][2]

IndexError: invalid index to scalar variable.

#### Deleting an elemnt in the array

In [33]:
arr=np.array([1,2,3,4])
# index 0=1,1=2,2=3,3=4

In [31]:
new_arr=np.delete(arr,2)

In [32]:
print(new_arr)

[1 2 4]


In [ ]:
arr=np.array([1,2,3,4])
# 1+5,2+5,3+5,4+5


In [35]:
print(arr+5)

[6 7 8 9]


In [36]:
print(arr*5)

[ 5 10 15 20]


In [37]:
print(arr-25)

[-24 -23 -22 -21]


In [38]:
arr1=([1,2,3])
arr2=([4,5,6])

In [39]:
arr1+arr2

[1, 2, 3, 4, 5, 6]